/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.18
 * Generated at: 2026-02-12 11:24:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class startTest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

/* ------------------ LOGIN CHECK ------------------ */
if(session.getAttribute("user") == null){
    response.sendRedirect("login.jsp");
    return;
}


/* ------------------ INITIALIZE TESTS (ONCE) ------------------ */
if(application.getAttribute("tests") == null){

    java.util.HashMap<String, String[][]> tests =
            new java.util.HashMap<>();

    /* -------- TEST 1 -------- */
    String[][] test1 = {
        {"Capital of India?","Delhi","Mumbai","Chennai","Kolkata","A"},
        {"2 + 2 = ?","3","4","5","6","B"},
        {"Sun rises in?","East","West","North","South","A"}
    };

    /* -------- TEST 2 -------- */
    String[][] test2 = {
        {"Linux creator?","Linus Torvalds","Bill Gates","Steve Jobs","Mark Zuckerberg","A"},
        {"HTTP default port?","21","22","80","443","C"},
        {"Which is a Linux distro?","Windows","Ubuntu","MacOS","DOS","B"}
    };

    tests.put("test1", test1);
    tests.put("test2", test2);

    application.setAttribute("tests", tests);
}


/* ------------------ GET SELECTED TEST ------------------ */
String testId = request.getParameter("testId");

if(testId == null){
    response.sendRedirect("dashboard.jsp");
    return;
}

java.util.HashMap<String, String[][]> tests =
    (java.util.HashMap<String, String[][]>)
    application.getAttribute("tests");

String[][] questions = tests.get(testId);

if(questions == null){
    response.sendRedirect("dashboard.jsp");
    return;
}


/* ------------------ INITIALIZE TEST SESSION ------------------ */
session.setAttribute("testId", testId);
session.setAttribute("questions", questions);
session.setAttribute("currentQuestion", 0);
session.setAttribute("answers",
        new java.util.HashMap<Integer,String>());


/* ------------------ CREATE RESUME COOKIE ------------------ */
/* (simple version for now, full resume later) */
Cookie resume = new Cookie("resume_test", testId + "|0");
resume.setMaxAge(60*60);
response.addCookie(resume);


/* ------------------ START TEST ------------------ */
response.sendRedirect("question.jsp");

      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
